import { Providers } from "@/provider/ThemeProvider";
import { TRPCProvider } from "@/trpc/client";
import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ausi.LK",
  description: "Generated by create next app",
  icons:
    "https://private-user-images.githubusercontent.com/139418339/475310430-516cf644-e5cd-4b18-943b-b611770a9e6b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxMzM2NzAsIm5iZiI6MTc1NTEzMzM3MCwicGF0aCI6Ii8xMzk0MTgzMzkvNDc1MzEwNDMwLTUxNmNmNjQ0LWU1Y2QtNGIxOC05NDNiLWI2MTE3NzBhOWU2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQwMTAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2ZiODE5ZGQyNjU0ZjU5ZDI2MjkxNDI3OTVlMzUxMDA0NmQ4M2M0MDZkYjNlYTlkOGVlMDVjMTM1OGU1M2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LRzx3btlDqmSrkvta5LOBBxLz0TPCPy1nMUVxcJv8vk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={jakarta.className}>
          <Providers>
            <TRPCProvider>
              <Toaster />
              {children}
            </TRPCProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
