import { Providers } from "@/provider/ThemeProvider";
import { TRPCProvider } from "@/trpc/client";
import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ausi.LK",
  description: "Generated by create next app",
  icons: "https://i.postimg.cc/GhbMr2vc/IMG-0126.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={jakarta.className}>
          <Providers>
            <TRPCProvider>
              <Toaster />
              {children}
            </TRPCProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
